// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpYcz5yeoLwun2bBF9HWAr3KUGPeZbN0U',
    appId: '1:1049928809020:android:f19d61939eb2fc2bcca139',
    messagingSenderId: '1049928809020',
    projectId: 'vestido-nation',
    storageBucket: 'vestido-nation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjFgK7jOAUzt-_uqRjDzOsRcW4ufPCWO8',
    appId: '1:1049928809020:ios:89ab008ec56f6975cca139',
    messagingSenderId: '1049928809020',
    projectId: 'vestido-nation',
    storageBucket: 'vestido-nation.firebasestorage.app',
    androidClientId: '1049928809020-am9ujt09jmj7261945gv7dq35m4bmfce.apps.googleusercontent.com',
    iosClientId: '1049928809020-7g1rrope8mujgj9bb0uj9cful2l80r6k.apps.googleusercontent.com',
    iosBundleId: 'com.vestidonation.app',
  );

}